#设置tomcat服务端口号
server:
  port : 8761
spring:
  application:
    name: eurekazz

eureka:
  client:
    fetch-registry: true #同步注册中心的信息
    register-with-eureka: true #注册中心注册自己
    service-url:
      defaultZone: http://peer2:8762/eureka #注册到注册中心
  instance:
    hostname: peer1
    instance-id: peer1